### ISSUE TITLE
Classes with 8 character length names

### ISSUE THREAD

**Issue by kevinniechen** [konaraddi/umd-course-vis#1]
e.g "CMSC498M" doesn't fit inside the textbox

**Comment by konaraddi** [comment]
I'm using https://umd.io to fetch the prerequisites and, unfortunately, the API doesn't fetch courses with an 8 character length. 

For example, making a GET request to https://api.umd.io/v0/courses/CMSC489M will return the response below:
```json
{"error_code":404,"message":"Course with course_id CMSC489M not found!","available_courses":"http://api.umd.io/v0/courses","docs":"http://umd.io/courses/"}
```
