### ISSUE TITLE
No visual sign if request fails

### ISSUE THREAD

**Issue by kevinniechen** [konaraddi/umd-course-vis#2]
e.g if internet is down, no way to know if request failed or if class simply doesn't exist

potential fixes:
- message on "class doesnt exist"
- message on "cannot connect to db"

**Comment by konaraddi** [comment]
Thanks for letting me know! Definitely need to handle those cases. There's currently no way to tell if a request failed, the class doesn't exist, or if there's just no prerequisites. 

I've added it to [the todo list](https://github.com/konaraddi/umd-course-vis/blob/master/TODO.md). Right now, I'm working on handling courses where there are "pick 1 course from blah blah" as a prerequisite (e.g. [CMSC412](https://app.testudo.umd.edu/soc/search?courseId=cmsc412&sectionId=&termId=201808&_openSectionsOnly=on&creditCompare=&credits=&courseLevelFilter=ALL&instructor=&_facetoface=on&_blended=on&_online=on&courseStartCompare=&courseStartHour=&courseStartMin=&courseStartAM=&courseEndHour=&courseEndMin=&courseEndAM=&teachingCenter=ALL&_classDay1=on&_classDay2=on&_classDay3=on&_classDay4=on&_classDay5=on)), so I'll get around to this issue once that's done. However, feel free to fork and submit a pull request for handling this issue.

EDIT: [MATH403](https://app.testudo.umd.edu/soc/search?courseId=math403&sectionId=&termId=201808&_openSectionsOnly=on&creditCompare=&credits=&courseLevelFilter=ALL&instructor=&_facetoface=on&_blended=on&_online=on&courseStartCompare=&courseStartHour=&courseStartMin=&courseStartAM=&courseEndHour=&courseEndMin=&courseEndAM=&teachingCenter=ALL&_classDay1=on&_classDay2=on&_classDay3=on&_classDay4=on&_classDay5=on) is a better example than CMSC412
